; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = cmsis
upload_protocol = stlink

build_flags = 
    -D USE_STDPERIPH_DRIVER   ; 告诉内核：我们要使用标准外设库
    -D STM32F10X_MD           ; 告诉内核：F103C8T6 是中容量芯片
    -I include                ; 确保系统能找到 stm32f10x_conf.h
    -I lib/SPL/include        ; 把标准库头文件暴露给全局所有代码